### ISSUE TITLE
Preparação dos dados

### ISSUE THREAD

**Issue by lucasjmatias** [lucasjmatias/big-data-projeto-final-analise-exporatoria-dados#1]
**account**:

- [ ] 1. date: preparar para data, atualmente está em "YYMMDD".
- [ ] 2. frequency: Traduzir status para inglês ou português.

**client**:

- [ ] birth: Valores são YYMMDD e YYMM+50DD, onde +50DD representa o sexo femínino. Formatar data e separar o campo de gênero, M e F.

**order**:
- [ ] K_symbol: Traduzir status para o português. POPLATEK MESICNE = "EMISSAO MENSAL"; POPLATEK TYDNE" = "EMISSAO SEMANAL"; "POPLATEK PO OBRATU" = "EMISSAO APOS TRANSACAO".

**transaction**:

- [ ] 	date: preparar para data, atualmente está em "YYMMDD".
- [ ] 	type: Traduzir status para o português. "PRIJEM" = "CREDITO"; "VYDAJ" = "DEBITO"
- [ ] 	operation: Traduzir status para inglês ou português. "VYBER KARTOU" = "SAQUE CREDITO";  "VYBER" = "SAQUE"; "VKLAD" = "DEPOSITO"; "PREVOD Z UCTU": "RECEBIMENTO OUTRO BANCO"; "PREVOD NA UCET": "ENVIO OUTRO BANCO"
- [ ] 	k_symbol: Traduzir status para o português. "POJISTNE" = "SEGURO"; "SLUZBY" = "PAGAMENTO DECLARACAO"; "UROK" = "JUROS CREDITADO"; "SANKC. UROK" = "JUROS DE MORA"; "SIPO" = "DOMESTICA"; "DUCHOD" = "PENSAO"; "UVER": "PAGAMENTO DE DIVIDA"

**Loan**:

- [ ] 	date: preparar para data, atualmente está em "YYMMDD".
- [ ] 	status: nomes mais amigáveis - "A": "FINALIZADO"; "B": "FINALIZADO NAO PAGO"; "C": "VIGENTE", "D": "VIGENTE EM DEBITO".
- [ ]  amount: converter de string para decimal.

**Credit card**:

- [ ] 	issued: preparar para data, atualmente está em "YYMMDD".

**Comment by cesarcostar** [comment]
Estou mandando
